### ISSUE TITLE
На мобильных устройствах теряется структура сайта

### ISSUE THREAD

**Issue by Sasha1345** [lelonco/lelonco.github.io#4]
![photo_2018-07-09_12-24-53](https://user-images.githubusercontent.com/40989705/42442385-344878b6-8373-11e8-97ea-0bd1bc77a8bb.jpg)
![photo_2018-07-09_12-25-01](https://user-images.githubusercontent.com/40989705/42442386-3465146c-8373-11e8-8271-cfe17fc89d96.jpg)
/сс @soul-wish”

**Comment by soul-wish** [comment]
@lelonco ты все пофиксил, или нет?
