### ISSUE TITLE
Верхнее меню

### ISSUE THREAD

**Issue by ppashkov** [lelonco/lelonco.github.io#5]
Я бы сделал верхнее меню скрывающимся при прокрутке.
![2018-07-09 12-34-12](https://user-images.githubusercontent.com/40775247/42442854-7fef34c0-8374-11e8-82d2-1ead53ae68a7.png)
![2018-07-09 12-34-15](https://user-images.githubusercontent.com/40775247/42442856-8011c12a-8374-11e8-9eb5-68dcb6dab065.png)
/сс @soul-wish

**Comment by lelonco** [comment]
DONE!
